const IOT_CONTROL_PANEL_ACTION_ACTIVATE = 501;
const IOT_CONTROL_PANEL_ACTION_PAUSE = 502;
const IOT_CONTROL_PANEL_ACTION_TURN_OFF = 503;
const IOT_CONTROL_PANEL_ACTION_SENSOR_DATA_SENT = 504;
const IOT_CONTROL_PANEL_ACTION_METADATA_SENT = 505;
const IOT_CONTROL_PANEL_ACTION_DEVICE_ID_SENT = 505;
const IOT_CONTROL_PANEL_ACTION_STATUS_CODE_SENT = 505;
