const MQTT_CLIENT_EVENT_CONNECT = 'connect';
const MQTT_CLIENT_EVENT_RECONNECT = 'reconnect';
const MQTT_CLIENT_EVENT_CLOSE = 'close';
const MQTT_CLIENT_EVENT_OFFLINE = 'offline';
const MQTT_CLIENT_EVENT_SUBSCRIBE = 'subscribe';
const MQTT_CLIENT_EVENT_MESSAGE = 'message';

export {
    MQTT_CLIENT_EVENT_CONNECT,
    MQTT_CLIENT_EVENT_RECONNECT,
    MQTT_CLIENT_EVENT_CLOSE,
    MQTT_CLIENT_EVENT_OFFLINE,
    MQTT_CLIENT_EVENT_SUBSCRIBE,
    MQTT_CLIENT_EVENT_MESSAGE,
};
