const MQTT_CLIENT_EVENT_CONNECT = 'connect';
const MQTT_CLIENT_EVENT_OFFLINE = 'offline';
const MQTT_CLIENT_EVENT_SUBSCRIBE = 'subscribe';
const MQTT_CLIENT_EVENT_MESSAGE = 'message';
const MQTT_CLIENT_EVENT_ERROR = 'error';
const MQTT_CLIENT_EVENT_PACKETSEND = 'packetsend';
const MQTT_CLIENT_EVENT_PACKETRECEIVE = 'packetreceive';
const MQTT_CLIENT_EVENT_RECONNECT = 'reconnect';
const MQTT_CLIENT_EVENT_CLOSE = 'close';

export {
    MQTT_CLIENT_EVENT_CONNECT,
    MQTT_CLIENT_EVENT_OFFLINE,
    MQTT_CLIENT_EVENT_SUBSCRIBE,
    MQTT_CLIENT_EVENT_MESSAGE,
    MQTT_CLIENT_EVENT_ERROR,
    MQTT_CLIENT_EVENT_PACKETSEND,
    MQTT_CLIENT_EVENT_PACKETRECEIVE,
    MQTT_CLIENT_EVENT_RECONNECT,
    MQTT_CLIENT_EVENT_CLOSE,
};
