const MQTT_CLIENT_EVENT_ON_CONNECT = 'connect';
const MQTT_CLIENT_EVENT_ON_CLOSE = 'close';
const MQTT_CLIENT_EVENT_ON_MESSAGE = 'message';

export {
    MQTT_CLIENT_EVENT_ON_CONNECT,
    MQTT_CLIENT_EVENT_ON_CLOSE,
    MQTT_CLIENT_EVENT_ON_MESSAGE,
};
