const DATA_ATTR_NODE_ACTION_TERMINAL = 'terminal';
const DATA_ATTR_NODE_ACTION_STREAMING_DATA = 'streaming-sensor-data';
const DATA_ATTR_NODE_ACTION_ANALYTICS = 'analytics';

export {
    DATA_ATTR_NODE_ACTION_TERMINAL,
    DATA_ATTR_NODE_ACTION_STREAMING_DATA,
    DATA_ATTR_NODE_ACTION_ANALYTICS,
};
